apiVersion: v2
name: pms-partner
description: A Helm chart for MOSIP Partner Management Service Partner service
type: application
version: 12.1.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - pms-partner
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
